export const INVOICE_GET_ALL = '[INVOICE] INVOICE_GET_ALL';
export const INVOICE_GET_ONE = '[INVOICE] INVOICE_GET_ONE';
export const INVOICE_CREATE  = '[INVOICE] INVOICE_CREATE';
export const INVOICE_UPDATE  = '[INVOICE] INVOICE_UPDATE';